### ISSUE TITLE
前端知识摘要

### ISSUE THREAD

**Issue by jianxiaofei** [jxfdemo/material#2]

**Comment by jxfdemo** [comment]
#easy-mock 本地搭建#
-----------------------
[参考文章：](https://www.jianshu.com/p/8c40dbda6e87)
### 安装redis
下载 http://download.redis.io/releases/redis-5.0.2.tar.gz 并解压
`
sudo mv redis-5.0.2 /usr/local/redis
cd /usr/local/redis
sudo make test
sudo make install
redis-server
`
### 安装mongodb
[到官网下载最对应版本:](https://www.mongodb.com/try/download/enterprise)
`sudo mv mongodb-osx-x86_64-4.2.0  /User/jianxiaofei/mongodb`
`cd 
open -e .bash_profile
`
添加环境变量

> export PATH= /User/jianxiaofei/mongodb/bin:${PATH}
`
cd
source .bash_profile
mongodb
`
如果上面这不正常
重启mac commond + R 进入恢复模式的终端输入csrutil disable 
再重启终端 sudo mount -uw /
之后就可以在根目录下创建目录： mkdir -p /data/db

### 安装easy-mock
`
git clone https://github.com/easy-mock/easy-mock.git
cd easy-mock && yarn
`
到easy-mock目录
`
nvm use 14.6.0
npm run dev
`
#完# 可以愉快的玩easy-mock了😁

**Comment by jxfdemo** [comment]
### easy-mock 常用命令

> {
  "success": true,
  "data": {
    "projects|3-10": [{          		 //数据数量3-10
      "id": "@id", 						//随机id
      "date": "@date(yyyy-MM-dd)" , //随机时间   年-月-日
      "datetime": "@datetime" ,        //随机时间   年-月-日 -当前时间
      "name": "@cname",     		//随机中文名字
      "url": "@url",                 		 //随机url 
      "email": "@email",					//随机Email地址
      "address": "@county(true)",   	 //随机地址，有三级
      "csentence": "@csentence(3,5)",     //随机中文字 3-5 个
      "string|1-10": "★",                              //随机★★  ||||||-  1-10个
      "number|1-100": 100,                     //随机数字   1-100
      "boolean|1-2": true,						//	随机状态： true | false
			  "status|1": [								// 随机状态 ：  三选一
	       "deleted", "published", "draft"
	     ]
    }]
  }
}
